---
- name: prerequisites
  hosts: servers
  roles:
    - prerequisites
    - install-jdk
    - install-jboss-eap
- name: start-domain
  hosts: jboss-domaincontroller
  roles:
    - start-domain-controller