---

- name: Check if jboss is installed
  stat:
    path: "/opt/jboss/jboss-eap-{{ jboss_version }}"
  register: jboss_installed

- name: Check if zip source file for jboss {{ jboss_version }} exists
  stat:
    path: "/tmp/jboss-eap-{{ jboss_version }}.zip"
  register: jboss_ressource
  when: not jboss_installed.stat.exists

- name: download sources jboss {{ jboss_version }}
  get_url:
    url: "https://access.cdn.redhat.com/content/origin/files/sha256/5f/5f1f0b7a389dedcd6f91ea3c8c6c9b723e9e8609bdf5720d4088e5469d46ad3a/jboss-eap-7.4.0.zip?_auth_=1688569416_17246aa5ad3857e3f470a9aca13cd4b5"
    dest: "/tmp/{{ jboss_version }}.zip"
  when: not jboss_ressource.stat.exists
  